-- additional plugins
reload "user.plugins"
reload "user.options"
reload "user.keymaps"
reload "user.autocommands"
reload "user.lsp"
reload "user.treesitter"
reload "user.copilot"
reload "user.telescope"
reload "user.fidget"
reload "user.whichkey"
reload "user.inlay-hints"
reload "user.functions"
reload "user.dial"

-- reload "user.chatgpt"
-- reload "user.neoai"
